### PR TITLE
refactor: integration of design patterns Factory Method and Strategy …

### PR DESCRIPTION
**Pull request by ronaldo-mendoza-jalafund**
…in validators

### CODE REVIEW

**Review by alex-paca-jalafund — COMMENTED** [review]
How is the strategy pattern and the factory pattern being implemented?

**Review by ronaldo-mendoza-jalafund — COMMENTED** [review]
I am applying Factory Method from the Bases folder which contains the abstract class BaseValidator<T>, which provides a basic implementation for validators, and the Concretes folder contains the concrete classes BookValidator and PatronValidator, which inherit from BaseValidator<T> and provide specific implementations for each type of object to be validated. In addition, the concrete classes BookValidator and PatronValidator use a Strategy design pattern, where private methods are defined that implement the specific validations for each field of the object to be validated.

**Comment by alex-paca-jalafund** [comment]
> I am applying Factory Method from the Bases folder which contains the abstract class BaseValidator, which provides a basic implementation for validators, and the Concretes folder contains the concrete classes BookValidator and PatronValidator, which inherit from BaseValidator and provide specific implementations for each type of object to be validated. In addition, the concrete classes BookValidator and PatronValidator use a Strategy design pattern, where private methods are defined that implement the specific validations for each field of the object to be validated

**Comment by alex-paca-jalafund** [comment]
ok , i see that its a modified pattern implementation, it works.

**Review by alex-paca-jalafund — APPROVED** [review]
Nice.

**Pull request merged**
